/* Auto-generated by genmsg_cpp for file /home/shehzad/catkin_ws/bosch_drivers/bmp085/msg/bmp085_measurement.msg */
#ifndef BMP085_MESSAGE_BMP085_MEASUREMENT_H
#define BMP085_MESSAGE_BMP085_MEASUREMENT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace bmp085
{
template <class ContainerAllocator>
struct bmp085_measurement_ {
  typedef bmp085_measurement_<ContainerAllocator> Type;

  bmp085_measurement_()
  : header()
  , is_connected(false)
  , temperature(0.0)
  , pressure(0.0)
  {
  }

  bmp085_measurement_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , is_connected(false)
  , temperature(0.0)
  , pressure(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint8_t _is_connected_type;
  uint8_t is_connected;

  typedef float _temperature_type;
  float temperature;

  typedef float _pressure_type;
  float pressure;


  typedef boost::shared_ptr< ::bmp085::bmp085_measurement_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bmp085::bmp085_measurement_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct bmp085_measurement
typedef  ::bmp085::bmp085_measurement_<std::allocator<void> > bmp085_measurement;

typedef boost::shared_ptr< ::bmp085::bmp085_measurement> bmp085_measurementPtr;
typedef boost::shared_ptr< ::bmp085::bmp085_measurement const> bmp085_measurementConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::bmp085::bmp085_measurement_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::bmp085::bmp085_measurement_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace bmp085

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::bmp085::bmp085_measurement_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::bmp085::bmp085_measurement_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::bmp085::bmp085_measurement_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e46f06afb39aba894bcfac63fab0dcc3";
  }

  static const char* value(const  ::bmp085::bmp085_measurement_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe46f06afb39aba89ULL;
  static const uint64_t static_value2 = 0x4bcfac63fab0dcc3ULL;
};

template<class ContainerAllocator>
struct DataType< ::bmp085::bmp085_measurement_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bmp085/bmp085_measurement";
  }

  static const char* value(const  ::bmp085::bmp085_measurement_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::bmp085::bmp085_measurement_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
bool is_connected # is the sensor connected?\n\
float32 temperature #[C]\n\
float32 pressure #[kPa]\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::bmp085::bmp085_measurement_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::bmp085::bmp085_measurement_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::bmp085::bmp085_measurement_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::bmp085::bmp085_measurement_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.is_connected);
    stream.next(m.temperature);
    stream.next(m.pressure);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct bmp085_measurement_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bmp085::bmp085_measurement_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::bmp085::bmp085_measurement_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "is_connected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_connected);
    s << indent << "temperature: ";
    Printer<float>::stream(s, indent + "  ", v.temperature);
    s << indent << "pressure: ";
    Printer<float>::stream(s, indent + "  ", v.pressure);
  }
};


} // namespace message_operations
} // namespace ros

#endif // BMP085_MESSAGE_BMP085_MEASUREMENT_H

