(cl:in-package bmc050_driver-msg)
(cl:export '(HEADER-VAL
          HEADER
          ACCELERATIONX-VAL
          ACCELERATIONX
          ACCELERATIONY-VAL
          ACCELERATIONY
          ACCELERATIONZ-VAL
          ACCELERATIONZ
          TEMPERATURE-VAL
          TEMPERATURE
          MAGNETICFIELDINTENSITYX-VAL
          MAGNETICFIELDINTENSITYX
          MAGNETICFIELDINTENSITYY-VAL
          MAGNETICFIELDINTENSITYY
          MAGNETICFIELDINTENSITYZ-VAL
          MAGNETICFIELDINTENSITYZ
          HALLRESISTANCE-VAL
          HALLRESISTANCE
))