(cl:defpackage bmp085-srv
  (:use )
  (:export
   "WEATHER_FORCAST"
   "<WEATHER_FORCAST-REQUEST>"
   "WEATHER_FORCAST-REQUEST"
   "<WEATHER_FORCAST-RESPONSE>"
   "WEATHER_FORCAST-RESPONSE"
   "MEASURE"
   "<MEASURE-REQUEST>"
   "MEASURE-REQUEST"
   "<MEASURE-RESPONSE>"
   "MEASURE-RESPONSE"
  ))

